No
No
No
No
11 13 18 
No
No
No
11 18 
No
No
11 18 
6 11 13 18 28 
No
No
No
11 
No
No
No
11 65 
No
No
No
No
No
6 11 13 18 
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
11 13 18 60 71 89 
No
No
11 13 18 60 71 89 
No
No
11 13 18 71 89 
No
No
No
No
No
No
No
No
No
11 13 18 71 89 
No
No
No
No
11 
No
6 11 13 18 28 
No
No
No
11 13 18 
No
No
No
No
No
No
No
No
No
11 13 18 44 60 71 89 
No
No
No
No
No
No
No
11 13 18 71 
No
No
No
No
No
No
No
No
No
No
No
