/*
 * MetadataPanel.java
 *
 * Created on June 3, 2005, 9:34 AM
 */

package j1viewer;

import java.awt.event.*;
import java.util.*;

/**
 *
 * @author  cmlee
 */
public class MetadataPanel extends javax.swing.JPanel {
    
    /** Creates new form MetadataPanel */
    public MetadataPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.TitledBorder("Meta Information"));
        jLabel1.setText("Image Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("* filename goes here *");
        jLabel2.setToolTipText("Image filename");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Photographer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel3, gridBagConstraints);

        jTextField1.setColumns(20);
        jTextField1.setToolTipText("Photographer's name");
        jTextField1.setNextFocusableComponent(jComboBox1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jTextField1, gridBagConstraints);

        jLabel4.setText("Date:");
        jLabel4.setToolTipText("Capture date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Category:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("Type:");
        jLabel6.setToolTipText("Image format");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel6, gridBagConstraints);

        jLabel7.setText("Rating:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel7, gridBagConstraints);

        jLabel8.setText("Comments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel8, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 3, 3));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox1.setToolTipText("Month");
        jComboBox1.setNextFocusableComponent(jComboBox2);
        jPanel1.add(jComboBox1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox2.setToolTipText("Day");
        jComboBox2.setNextFocusableComponent(jComboBox3);
        jPanel1.add(jComboBox2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        jComboBox3.setToolTipText("Year");
        jComboBox3.setNextFocusableComponent(jComboBox4);
        jPanel1.add(jComboBox3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jPanel1, gridBagConstraints);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nature", "People", "Places" }));
        jComboBox4.setToolTipText("Photo classification");
        jComboBox4.setNextFocusableComponent(jSlider1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jComboBox4, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 3, 3));

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("GIF");
        jRadioButton1.setEnabled(false);
        jPanel2.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("JPEG");
        jRadioButton2.setEnabled(false);
        jPanel2.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("TIFF");
        jRadioButton3.setEnabled(false);
        jPanel2.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("BMP");
        jRadioButton4.setEnabled(false);
        jPanel2.add(jRadioButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jPanel2, gridBagConstraints);

        jSlider1.setMajorTickSpacing(2);
        jSlider1.setMaximum(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText(" My rating for this photo: 0(bad) - 10(good)");
        jSlider1.setValue(5);
        jSlider1.setNextFocusableComponent(jTextArea1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jSlider1, gridBagConstraints);

        jTextArea1.setRows(7);
        jTextArea1.setToolTipText("Comments");
        jTextArea1.setNextFocusableComponent(jButton1);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel3.setBorder(new javax.swing.border.EtchedBorder());
        jButton1.setIcon(new javax.swing.ImageIcon("/home/cmlee/src/hol/netbeansswing/resources/Save24.gif"));
        jButton1.setText("Modify");
        jButton1.setToolTipText("Save changes");
        jButton1.setNextFocusableComponent(jTextField1);
        jPanel3.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel3, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Getter for property imageFilename.
     * @return Value of property imageFilename.
     */
    public String getImageFilename() {
        
        return (jLabel2.getText());
    }
    
    /**
     * Setter for property imageFilename.
     * @param imageFilename New value of property imageFilename.
     */
    public void setImageFilename(String imageFilename) {
        
        jLabel2.setText(imageFilename);
    }
    
    /**
     * Getter for property photographerName.
     * @return Value of property photographerName.
     */
    public String getPhotographerName() {
        return (jTextField1.getText());
    }
    
    /**
     * Setter for property photographerName.
     * @param photographerName New value of property photographerName.
     */
    public void setPhotographerName(String photographerName) {
        jTextField1.setText(photographerName);
    }
    
    /**
     * Getter for property captureDate.
     * @return Value of property captureDate.
     */
    public java.util.Date getCaptureDate() {
        GregorianCalendar cal = new GregorianCalendar(
                (jComboBox3.getSelectedIndex() + 2000) /* year */
                , jComboBox1.getSelectedIndex() /* month */
                , jComboBox2.getSelectedIndex() /* day */);
        
        return (cal.getTime());
    }
    
    /**
     * Setter for property captureDate.
     * @param captureDate New value of property captureDate.
     */
    public void setCaptureDate(java.util.Date captureDate) {
        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(captureDate);
        //set month
        jComboBox1.setSelectedIndex(cal.get(Calendar.MONTH));
        //set day
        jComboBox2.setSelectedIndex(cal.get(Calendar.DATE));
        //set year - Potential error. Should do more checks here
        jComboBox3.setSelectedIndex(cal.get(Calendar.YEAR) - 2000);
    }
    
    /**
     * Getter for property category.
     * @return Value of property category.
     */
    public j1viewer.Categories getCategory() {
        switch (jComboBox4.getSelectedIndex()) {
            case 0:
                return (j1viewer.Categories.Nature);
            case 1:
                return (j1viewer.Categories.People);
            default:
                return (j1viewer.Categories.Places);
        }
    }
    
    /**
     * Setter for property category.
     * @param category New value of property category.
     */
    public void setCategory(j1viewer.Categories category) {
        int idx;
        switch (category) {
            case Nature:
                idx = 0;
                break;
            case People:
                idx = 1;
                break;
            default:
                idx = 2;
        }
        jComboBox4.setSelectedIndex(idx);
    }
    
    /**
     * Getter for property imageFormat.
     * @return Value of property imageFormat.
     */
    public j1viewer.ImageFormat getImageFormat() {
        if (jRadioButton1.isSelected())
            return (ImageFormat.GIF);
        else if (jRadioButton2.isSelected())
            return (ImageFormat.JPEG);
        else if (jRadioButton3.isSelected())
            return (ImageFormat.TIFF);
        else
            return (ImageFormat.BMP);
    }
    
    /**
     * Setter for property imageFormat.
     * @param imageFormat New value of property imageFormat.
     */
    public void setImageFormat(j1viewer.ImageFormat imageFormat) {
        switch (imageFormat) {
            case GIF:
                jRadioButton1.setSelected(true);
                return;
            case JPEG:
                jRadioButton2.setSelected(true);
                return;
            case TIFF:
                jRadioButton3.setSelected(true);
                return;
            default:
                jRadioButton4.setSelected(true);
                return;
        }
    }
    
    /**
     * Getter for property ratings.
     * @return Value of property ratings.
     */
    public int getRatings() {
        return (jSlider1.getValue());
    }
    
    /**
     * Setter for property ratings.
     * @param ratings New value of property ratings.
     */
    public void setRatings(int ratings) {
        jSlider1.setValue(ratings % jSlider1.getMaximum());
    }
    
    /**
     * Getter for property comments.
     * @return Value of property comments.
     */
    public String getComments() {
        return (jTextArea1.getText());
    }
    
    /**
     * Setter for property comments.
     * @param comments New value of property comments.
     */
    public void setComments(String comments) {
        jTextArea1.setText(comments);
    }

    public void addActionListener(ActionListener listener) {
        jButton1.addActionListener(listener);
    }
    
}
